### ISSUE TITLE
Has a wrong about GetDiagnosticsRequest  parameter?

### ISSUE THREAD

**Issue by MingShyanWei** [lorenzodonini/ocpp-go#138]
In file:
./ocpp1.6/firmware/get_diagnostics.go
<img width="904" alt="image" src="https://user-images.githubusercontent.com/6902864/187120006-5e0f97f9-066d-4d46-a97c-c60702edd4f5.png">

"stopTime" is different from the Specification 
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/6902864/187119626-1f1b8395-8738-496e-9cb1-141d7df0f6a8.png">

**Comment by lorenzodonini** [comment]
Thanks for noticing this. I just merged a fix to master. Will release a new version in the next days.
