### ISSUE TITLE
ChargingProfileStatus NotImplemented should be NotSupported

### ISSUE THREAD

**Issue by heavyweight87** [lorenzodonini/ocpp-go#161]
Hi,

We were sending status NotSupported and receiving an error. Turns out that it is incorrectly called NotImplemented: [here] https://github.com/lorenzodonini/ocpp-go/blob/956223d45e767a294840642385e48d298f925fd6/ocpp1.6/smartcharging/set_charging_profile.go#L20)

According to the 1.6 standard it should be NotSupported

Thanks

**Comment by lorenzodonini** [comment]
Nice catch, thanks! 

Fixed it on master branch.
