### ISSUE TITLE
OCPP 2.0.1 support

### ISSUE THREAD

**Issue by nikunjtilva** [lorenzodonini/ocpp-go#19]
I see you are actively working on ocpp 2.0 branch. Since ocpp 2.0.1 was released in March this year are you already considering it? And compliments for a great work!!

**Comment by lorenzodonini** [comment]
Hello and thanks for checking out my repo.

Yes, I am considering implementing all the fixes/improvements introduced in version 2.0.1 directly (official specifications recommend doing so). You might not see them in the code yet, as I was already working on the 2.0 implementation before 2.0.1 was released. In any case I will try support v2.0.1 out-of-the-box.

**Comment by nikunjtilva** [comment]
Good to know this...Thanks for quick reply...
