### ISSUE TITLE
type Transaction struct - StoppedReason - Type -> TriggerReason?

### ISSUE THREAD

**Issue by qosmotec** [lorenzodonini/ocpp-go#199]
Hi Lorenzo,

should'nt be Transaction.StoppedReason of Type transactions.TriggerReason

Thanks for checking

**Comment by lorenzodonini** [comment]
Hey,

you might be confusing the `ReasonEnum` with the `TriggerReasonEnum` types.

According to the specs, a `TransactionEventRequest` contains a `TriggerReason` field and a `TransactionInfo` field. The latter in turn contains an optional `StoppedReason` field.

<img width="967" alt="Screenshot 2023-06-04 at 10 46 17" src="https://github.com/lorenzodonini/ocpp-go/assets/7532913/bc6bf3c8-3535-4129-82e8-7997f1eb0a20">

<img width="967" alt="Screenshot 2023-06-04 at 10 48 15" src="https://github.com/lorenzodonini/ocpp-go/assets/7532913/e41e2f67-5348-45bc-83b7-c59bbba2dd21">
