### ISSUE TITLE
Infinite wait on stopping a disconnected charge point

### ISSUE THREAD

**Issue by adippel** [lorenzodonini/ocpp-go#203]
Just discovered that calling 
https://github.com/lorenzodonini/ocpp-go/blob/e034d3913431284a4241948c6ecb91aa6982758c/ocpp1.6/charge_point.go#L341

leads to an infinite loop when the charge point is already disconnected from the central system. This is due to a bug in:

https://github.com/lorenzodonini/ocpp-go/blob/e034d3913431284a4241948c6ecb91aa6982758c/ocppj/client.go#L108-L118

Waiting for a message on `cleanupC` that is expected to be sent when the underlying web socket connection is closed is just not feasible on an already closed web socket connection.

Registering the callback handler depending on the current connection state should do the trick. Simply closing the channel when we are already disconnected avoids the infinite loop.

This might be a starter for a patch:

```go
func (c *Client) Stop() {
	// Overwrite handler to intercept disconnected signal
	cleanupC := make(chan struct{}, 1)
	if c.client.IsConnected() {
		c.client.SetDisconnectedHandler(func(err error) {
			cleanupC <- struct{}{}
		})
	} else {
		close(cleanupC)
	}

	c.client.Stop()
	c.dispatcher.Stop()
	// Wait for websocket to be cleaned up
	<-cleanupC
}
```

I am happy to provide a PR for this or discuss this issue further.

**Comment by lorenzodonini** [comment]
Thanks for finding this edge case. I have a branch open with a fix based on the suggested code. It actually needs one more tweak in the lower websocket layer to prevent follow-up errors. I'm working on that and will write a test case to verify this.
