### ISSUE TITLE
Firmware Status Notification

### ISSUE THREAD

**Issue by MattGrouchy** [lorenzodonini/ocpp-go#213]
The OCPP 2.0.1 ID L02.FR.06:

> Every FirmwareStatusNotificationRequest sent
for a firmware update SHALL contain the same
requestId as the UpdateFirmwareRequest that
started this firmware update.

How can I provide the requestId to the ChargingStation.FirmwareStatusNotification method?

**Comment by lorenzodonini** [comment]
The `RequestID` field is optional and may be set in one of two ways.

### Option 1
```go
cs := ocpp2.NewChargingStation(...)
someRequestID := 42
resp, err := cs.FirmwareStatusNotification(firmware.FirmwareStatusDownloading, func(request *firmware.FirmwareStatusNotificationRequest) {
    request.RequestID = &someRequestID
})
// Handle response/error
```

### Option 2
```go
cs := ocpp2.NewChargingStation(...)
someRequestID := 42
req := firmware.NewFirmwareStatusNotificationRequest(firmware.FirmwareStatusDownloading)
req.RequestID = &someRequestID
resp, err := cs.SendRequest(req)
// Handle response/error
```

The approach via variadic function paramter holds true for setting every optional field.

Does this answer your question?

**Comment by MattGrouchy** [comment]
Yes, thank you!
