### ISSUE TITLE
Race condition in chargePoint.Start()

### ISSUE THREAD

**Issue by andig** [lorenzodonini/ocpp-go#227]
`chargePoint.Start()` sets global variable

    ocppj.FormationViolation = ocppj.FormatViolationV16

Same variable is written by `centralSystem.Start()` which creates a race condition during test.

This is particularly problematic since `centralSystem.Start()` cannot be serialised, i.e. it is not clear when the cs actually _has_ started.

**Comment by andig** [comment]
A potential workaround could be to use `dispatcher.IsRunning()` to determine if at least the cs' Go routine has started. This leads to another race. While `dispatcher.IsRunning()` uses mutex, `DefaultServerDispatcher.Start()` does not serialise its access to `d.running`. I can provide a PR for this second race.

**Comment by andig** [comment]
@lorenzodonini thank you for the quick merge. Could we keep this issue open? The workaround is now fixed, the race in `ocppj.FormatViolationV16` still present. I you can give a hint what this value- shared between CS and CP- should do I could take another look.

**Comment by andig** [comment]
Looks like there is a design issue with `FormationViolation`. It is used for creating error messages in `ocppj.Endpoint`. Instead of global variable it should be part of endpoint defintion.

**Comment by lorenzodonini** [comment]
I agree this should be an override within the endpoint instead of a global variable. I re-opened the issue and will move the discussion to the open branch.
