### ISSUE TITLE
TriggerMessage.Req validation disallows passing connector 0

### ISSUE THREAD

**Issue by atschabu** [lorenzodonini/ocpp-go#244]
According to OCPP 1.6 specs we can provide connectorID 0 (it is one of the examples), but the validator asks for `> 0` instead of `>= 0`

> Inversely, if the connectorId is relevant but absent, this should be interpreted as “for all allowed connectorId values”. For example, a request for a statusNotification for connectorId 0 is a request for the status of the Charge Point. A request for a statusNotification without connectorId is a request for multiple statusNotifications: the notification for the Charge Point itself and a notification for each of its connectors.

https://github.com/lorenzodonini/ocpp-go/blob/d214d7c42cbc2ae8be4ea9d97c007c23f72f3217/ocpp1.6/remotetrigger/trigger_message.go#L50

**Comment by lorenzodonini** [comment]
This is from the spec:

<img width="966" alt="Screenshot 2023-11-26 at 17 18 10" src="https://github.com/lorenzodonini/ocpp-go/assets/7532913/ec6196a2-98aa-4a15-9cae-897f09d6432a">

The `connectorId` is optional, so the way I interpret it:
- if omitted, the trigger will apply to all connectors
- if included, it shall refer to a specific connector (0 is not a connector)

**Comment by atschabu** [comment]
@andig 
>  where does it day that connector id 0 is valid?

besides the example having a clear usage of connector with id 0, you can also find it in the definition of the requests that we can trigger
<img width="1137" alt="image" src="https://github.com/lorenzodonini/ocpp-go/assets/5340333/58170cdf-6359-45e2-a6b0-2095cfce3f76">
<img width="1130" alt="image" src="https://github.com/lorenzodonini/ocpp-go/assets/5340333/f4a23284-37f7-47ad-8d24-e3e0756f1bf5">

**Comment by andig** [comment]
Looks like connectorId is differently specified per message typ

**Comment by lorenzodonini** [comment]
What @andig said is true, however I dug a bit deeper and realized there's probably an inconsistency in the spec. Here's a quote regarding the `TriggerMessage.req`:
> Inversely, if the connectorId is relevant but absent, this should be interpreted as “for all allowed connectorId values”. For example, a request for a statusNotification for connectorId 0 is a request for the status of the Charge Point. A request for a statusNotification without connectorId is a request for multiple statusNotifications: the notification for the Charge Point itself and a notification for each of its connectors.

This would indicate that at least for `StatusNotification` triggers, value `0` would indeed be allowed.

In doubt, I will change the validation and allow `>= 0`.
