### ISSUE TITLE
Parses an OCPP-J message，Occurrence anomaly

### ISSUE THREAD

**Issue by Kinrosslong** [lorenzodonini/ocpp-go#267]
Hello, this is the first time for me to submit an issue on github, please forgive me if it is not good or not standard. I encountered an exception message parsing error while using the repackage, which caused my service to crash. The error was reported in the ocppj/ocppj.go file ParseMessage() method. If the device sends [3, "",{"fileName": "diagnostics_file2.log"}] A message command such as this causes the CALL_RESULT to parse the request, Ok: = pendingRequestState. GetPendingRequest (uniqueId) in the request is nil, causing collapse program exit.

**Comment by xBlaz3kx** [comment]
Hi @Kinrosslong, 

it would help if you added a whole stack trace. From the description, it seems like the charge point does not send a unique request ID, so the central system isn't able to respond to the request. 

`[3, "",{"fileName": "diagnostics_file2.log"}]` - The second element in the array is missing, should be something like `"100124"`.

**Comment by Kinrosslong** [comment]
ok

lorenzodonini ***@***.***> 于2024年4月3日周三 00:50写道：

**Comment by Kinrosslong** [comment]
Yes is an error caused by the second parameter being empty. What I want to
express is that some equipment manufacturers do not professionally empty
the second parameter. The system reported an error. We should be able to
guard against that.
Thanks for your answers and good luck。

KK


Blaž Dular ***@***.***> 于2024年4月2日周二 19:53写道：
