### ISSUE TITLE
shoudl idTag validator be altered?

### ISSUE THREAD

**Issue by sc-atompower** [lorenzodonini/ocpp-go#277]
We are coming across OCPP central station vendors who are using OCPP for free and open charging thus not supplying or requiring an IdTag.

Currently we have `	IdTag         string          json:"idTag" validate:"required,max=20"`

Should we alter this or should we supply a fake idTag?

**Comment by sbindzau** [comment]
OCPP requires the tag so I would not remove the requirement. The solutions I have seen have a specific (settable) tag used for these transactions.

**Comment by lorenzodonini** [comment]
Agreed with @sbindzau. So basically a fake idTag (pre-shared secret). 

As for most users of the lib: if the official validation is too restrictive and doesn't suit you, it can simply be disabled:
```go
ocppj.SetMessageValidation(false)
```

**Comment by sc-atompower** [comment]
Thanks all. It also appears there is a freeVendTag in some ocpp configs for this use.
