### ISSUE TITLE
Authorize request missing connectorId?

### ISSUE THREAD

**Issue by andig** [lorenzodonini/ocpp-go#279]
In https://github.com/evcc-io/evcc/issues/14579#issuecomment-2203481347 we're seeing `Authorize` requests containing `connectorId`:

```
recv: [2, "1d2bd940-3149-11ef-9265-000a1484c32e", "Authorize", {"connectorId": 2, "idTag": "0584350940cxxx"}]
sent: [3,"1d2bd940-3149-11ef-9265-000a1484c32e",{"idTagInfo":{"status":"Accepted"}}]
```

For our use case that's required since we need to know which vehicle/rfid is connected to which connector.

However, the OCPP 1.6 spec version I have doesn't seem to include it: 

<img width="631" alt="Screenshot 2024-07-02 at 18 52 29" src="https://github.com/lorenzodonini/ocpp-go/assets/184815/11d4447c-f8e1-47a8-8d70-23f353fc9bd0">

How wide spread is the presence of `connectorId` in multi-connector boxes and would it be worth allowing it (against spec)?

Btw: seems the trace prints sent and received messages differently.

**Comment by lorenzodonini** [comment]
What's the use-case? Typically there is a single RFID reader on a wallbox (completely decoupled from the available connectors), hence the target connector ID is not even known at authorization time. It will be sent to the server later via `StartTransaction` (which will also contain the authorized idToken).

Just for clarity: this behavior is retained throughout OCPP v2, meaning it is considered standard. This makes me very hesistant to just deviate from it and add custom stuff.

**Comment by andig** [comment]
Thank you for the feedback.

> Typically there is a single RFID reader on a wallbox

I see. Our use case is identifying the connected vehicle via RFID tag. Seems this approach just doesn't work for multi connector boxes. Thank you!

**Comment by lorenzodonini** [comment]
@andig you may want to check this article out: https://openchargealliance.org/wp-content/uploads/2024/03/ocpp_1_x_multiple_connectors_per_evse-1.pdf. The last page contains a suggested workaround (not sure if it can be helpful for your case).

**Comment by andig** [comment]
Thank you. Think we will try to just record the idtag on authorize and then apply to the next connector that changes its state. Sounds like a plausible heuristic.
