### ISSUE TITLE
No Boot response from CS in 1.6 Docker?

### ISSUE THREAD

**Issue by andig** [lorenzodonini/ocpp-go#35]
I've just tried to use https://github.com/voltbras/go-ocpp with the CS docker image. When CP sends BootNotification, it never receives a response. Could you confirm if that is the expected behavior?

**Comment by lorenzodonini** [comment]
This is definitely not intended. Can you confirm whether the CS received the request and also sent the response correctly?

I have never tested this with eduhenke's implementation, but I can confirm the whole flow was working fine with other commercial implementations (tested during OCPP 1.6 plugfest last July).

If you can provide me with some logs/setup info I can look into it.

**Comment by andig** [comment]
I'm currently not sure if eduhenke is really functional. I'll retry with a client based on this repo and will double-check. Sorry for the noise.

**Comment by andig** [comment]
Closing until I can repro with cp from this repo. Thank you!
