### ISSUE TITLE
Charge point disconnects after 1 minute

### ISSUE THREAD

**Issue by paulhobbel** [lorenzodonini/ocpp-go#44]
Due to the way the pongWait is hardcoded in the ws server there is no way for me to increase the ping rate.
The charge points we use ping every 2 minutes. I suggest to make this configurable, for now I've copied over the ws server and modified the code to accept pings every 2 minutes

**Comment by lorenzodonini** [comment]
You have a good point there. Working on making this easily configurable.

**Comment by lorenzodonini** [comment]
@paulhobbel I created a PR with support for websocket timeout configuration. 

Feel free to check out https://github.com/lorenzodonini/ocpp-go/pull/46 and leave some feedback.

**Comment by paulhobbel** [comment]
This does exactly what I need it to do 👍
