### ISSUE TITLE
Contribution to OCPP 2.X

### ISSUE THREAD

**Issue by SerzhSergeev** [lorenzodonini/ocpp-go#51]
Hi guys!
@lorenzodonini I'm wondering if you have any roadmap/plan for integration latest OCPP 2.0 in this repository.
As far as I see the version 2.0 only stating here. I'd like to discuss it with you and maybe help from my side with that OCPP, please contact me if you're keen to sync on it.

**Comment by lorenzodonini** [comment]
Hey and thanks for reaching out.

You can check the [ocpp2.0-features](https://github.com/lorenzodonini/ocpp-go/tree/ocpp2.0-features/ocpp2.0) branch to see the current status. I'm planning on finishing the implementation of v2.0.1 soon and then release an alpha version.

You are of course welcome to send me a pull request, in case you want to implement some of the messages yourself. It's a bit of work though, so let me know if you would like to help out 😄

**Comment by strowk** [comment]
Could you please update on this? Was 2.0 finished? Branch is not there anymore...
