### ISSUE TITLE
ParseRawJsonMessage fatal app

### ISSUE THREAD

**Issue by anastasiyaIlyushko** [lorenzodonini/ocpp-go#52]
Hi!
Fix ParseRawJsonMessage return error instead fatal in https://github.com/lorenzodonini/ocpp-go/blob/master/ocppj/ocppj.go#L170 please

**Comment by lorenzodonini** [comment]
Hey, thanks for reaching out.

I have fixed this already in my current working branch. 
Will merge it soon and update you.

**Comment by lorenzodonini** [comment]
Solved in commit 6e08a29 and merged to master already. Will create a release with all the latest changes and improvements soon.
