### ISSUE TITLE
Shouldn't use errors

### ISSUE THREAD

**Issue by andig** [lorenzodonini/ocpp-go#54]
In https://github.com/lorenzodonini/ocpp-go/commit/ca11385f43267ce85e31c58343aaf18c39b0a457#diff-a39f6425f40fcc72579d309f8803af9677d6ae6ce92376a6214f339d42ea5050R9 the errors package is deprecated. Imho `fmt.Errorf` is the standard library's way to go

**Comment by lorenzodonini** [comment]
I didn't know the errors package is deprecated (huge changes introduced in 1.13), also haven't found that info anywhere. Any source?

In any case, I replaced all `errors` invocations with `fmt.Errorf` to have a consistent approach.

Closing this one.
