### ISSUE TITLE
Panic when TriggerMessage and Change/Get Configuration are called at the same time

### ISSUE THREAD

**Issue by utsavanand2** [lorenzodonini/ocpp-go#67]
## The Problem
I've have a cron job that sends a `TriggerMessage` request to the charging station every 30 seconds, I also have a rest API that can call `ChangeConfiguration` and `GetConfiguration` on the charging station.
When either the cron job or the REST API invokes the CSMS there's no panic, but when both of them are invoking the above two calls - `TriggerMessage` and `Change/Get Configuration` respectively, then I get this panic
<img width="1466" alt="Screenshot 2021-04-21 at 2 05 43 PM" src="https://user-images.githubusercontent.com/25264581/115523975-44a98600-a2ab-11eb-8bf5-65c218d41e82.png">

@lorenzodonini Can you point me in the right direction for a possible fix for this issue?

Though I'm yet to test if the latest changes to the library are something that can fix this issue. I'll test it out and make further comments about it.

## OCPP Version
1.6

**Comment by utsavanand2** [comment]
Closing this issue as it is fixed with the latest commits to this repo. Thanks a lot!

**Comment by lorenzodonini** [comment]
Hey there,

yes this was a bug we found out recently. 
There's a similar bug on the charge point counterpart, which I've fixed and will merge soon.

**Comment by utsavanand2** [comment]
Thanks a lot 🌟
